// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcgpjygoflazsdnyrthm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjZ3BqeWdvZmxhenNkbnlydGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MTI2NTcsImV4cCI6MjA2MTk4ODY1N30.ch3zzXgS4U6TBLgyZKaNXD2J2RyXRXEC5Xj4C3ycV4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);